

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    networks:
      - app_network
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - app_network
    ports:
      - "80:80"
      - "443:443"  # Port 443 pour SSL
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./SSL:/etc/nginx/ssl:ro  # Monter le dossier contenant les certificats SSL

networks:
  app_network:
    driver: bridge
